name: Java Maven Build & Publish Artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # manually triggering workflow
  workflow_dispatch:
    branches: [ "main" ]


jobs:
  build_test: # CI part

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # actions can be found in https://github.com/marketplace
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven # caches all dependencies
      - name: Build with Maven
        run: mvn -B package --file pom.xml # generates .jar file in target folder


  publish-job: # CD part
    runs-on: ubuntu-latest
    needs: build_test # this job is only executed if build_test was succesfull
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn --batch-mode --update-snapshots verify # update dependencies, and run integration tests
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging